message ("ENABLE_XENGINE_SNPE_NN: ${ENABLE_XENGINE_SNPE_NN}")
if(ENABLE_XENGINE_SNPE_NN)
    target_compile_options(${XENGINE_LIBRARY_NAME} PRIVATE -DHAVE_HAL_SNPE)
    
    if(SNPE_VERSION STREQUAL "snpe-1.55.0")
        target_compile_options(${XENGINE_LIBRARY_NAME} PRIVATE -DSNPE_VERSION=1550)
    endif()
    if(SNPE_VERSION STREQUAL "snpe-1.61.0")
        target_compile_options(${XENGINE_LIBRARY_NAME} PRIVATE -DSNPE_VERSION=1610)
    endif()
    if(SNPE_VERSION STREQUAL "snpe-1.66.0")
        target_compile_options(${XENGINE_LIBRARY_NAME} PRIVATE -DSNPE_VERSION=1660)
    endif()
    if(SNPE_VERSION STREQUAL "snpe-2.17.0")
        target_compile_options(${XENGINE_LIBRARY_NAME} PRIVATE -DSNPE_VERSION=2170)
    endif()
    
    set(pattern_snpe2 "snpe-2\.[0-9]+\.[0-9]+")
    string(REGEX MATCH "${pattern_snpe2}" match_snpe2 "${SNPE_VERSION}")
    message("match_snpe2=" ${match_snpe2})
    
    if(match_snpe2)
        add_subdirectory(vendor_snpe2)
    else()
        add_subdirectory(vendor_snpe)
    endif()
endif()

message ("ENABLE_XENGINE_MNN_NN: ${ENABLE_XENGINE_MNN_NN}")
if(ENABLE_XENGINE_MNN_NN)
    target_compile_options(${XENGINE_LIBRARY_NAME} PRIVATE -DHAVE_HAL_MNN)
    add_subdirectory(vendor_mnn)
endif()

add_subdirectory(vendor_xrnn)