set(HANDTRACKING_INTERFACE_LIBRARY_NAME nr_hand_tracking)

add_library(${HANDTRACKING_INTERFACE_LIBRARY_NAME} SHARED
${CMAKE_CURRENT_SOURCE_DIR}/handtracking_sdk_interface.cpp
)

# add target include. not fix exteral xxx.h 
target_include_directories(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE "./")

target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE 
-DHANDTRACKING_SHARED_LIBS 
-DNRPLUGIN 
-DAISK_GIT_VERSION="${GIT_CURRENT_BRANCH}:${GIT_LAST_COMMIT}"
-DNetAlgoLibName="nr_hand_algo"
-DSNPE_VERSION="2.0.0"
)

if(ENABLE_XENGINE_SNPE_NN)
    target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE -DHAVE_HAL_SNPE)
endif()

target_link_libraries(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PUBLIC base jsoncpp Eigen3::Eigen opencv::opencv)

install(TARGETS ${HANDTRACKING_INTERFACE_LIBRARY_NAME}
            LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
            RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
            ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
add_clang_format_target(${HANDTRACKING_INTERFACE_LIBRARY_NAME})

