set(HANDTRACKING_INTERFACE_LIBRARY_NAME nr_hand_tracking)

add_library(${HANDTRACKING_INTERFACE_LIBRARY_NAME} SHARED
${CMAKE_CURRENT_SOURCE_DIR}/handtracking_sdk_interface.cpp
)

# add target include. not fix exteral xxx.h
target_include_directories(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE "./")

target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE
-DHANDTRACKING_SHARED_LIBS
-DNRPLUGIN
-DAISK_GIT_VERSION="${GIT_CURRENT_BRANCH}:${GIT_LAST_COMMIT}"
PRIVATE -Wno-error
)

if(ENABLE_XENGINE_SNPE_NN)
    target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE -DHAVE_HAL_SNPE)

    if(SNPE_VERSION STREQUAL "snpe-1.55.0")
        target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE -DSNPE_VERSION=1550)
    endif()
    if(SNPE_VERSION STREQUAL "snpe-1.61.0")
        target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE -DSNPE_VERSION=1610)
    endif()
    if(SNPE_VERSION STREQUAL "snpe-1.66.0")
        target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE -DSNPE_VERSION=1660)
    endif()
    if(SNPE_VERSION STREQUAL "snpe-2.17.0")
        target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE -DSNPE_VERSION=2170)
    endif()
endif()


if(ENABLE_XENGINE_SHARED_LIB)
    target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE -DXENGINE_SHARED_LIB -DXENGINE_LIB_NAME="nr_hand_algo")
else()
    target_compile_options(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PRIVATE -DXENGINE_STATIC_LIB)
endif()

target_link_libraries(${HANDTRACKING_INTERFACE_LIBRARY_NAME} PUBLIC base algorithm jsoncpp Eigen3::Eigen opencv::opencv)

install(TARGETS ${HANDTRACKING_INTERFACE_LIBRARY_NAME}
            LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
            RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
            ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
add_clang_format_target(${HANDTRACKING_INTERFACE_LIBRARY_NAME})

