// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nreal.ai.tool.proto

#include "nreal.ai.tool.grpc.pb.h"

#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/server_context.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/support/sync_stream.h>

#include <functional>

#include "nreal.ai.tool.pb.h"
namespace NrealAiTool {

static const char* Engine_method_names[] = {
    "/NrealAiTool.Engine/Status",
    "/NrealAiTool.Engine/Upload",
    "/NrealAiTool.Engine/ResetSdk",
    "/NrealAiTool.Engine/StartSdk",
    "/NrealAiTool.Engine/StopSdk",
    "/NrealAiTool.Engine/PipelineInference",
    "/NrealAiTool.Engine/GetPipelineResult",
    "/NrealAiTool.Engine/SetServiceFeature",
    "/NrealAiTool.Engine/GetServiceActualInfo",
};

std::unique_ptr<Engine::Stub> Engine::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel,
                                              const ::grpc::StubOptions& options) {
    (void)options;
    std::unique_ptr<Engine::Stub> stub(new Engine::Stub(channel, options));
    return stub;
}

Engine::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
    : channel_(channel),
      rpcmethod_Status_(Engine_method_names[0], options.suffix_for_stats(), ::grpc::internal::RpcMethod::NORMAL_RPC,
                        channel),
      rpcmethod_Upload_(Engine_method_names[1], options.suffix_for_stats(), ::grpc::internal::RpcMethod::NORMAL_RPC,
                        channel),
      rpcmethod_ResetSdk_(Engine_method_names[2], options.suffix_for_stats(), ::grpc::internal::RpcMethod::NORMAL_RPC,
                          channel),
      rpcmethod_StartSdk_(Engine_method_names[3], options.suffix_for_stats(), ::grpc::internal::RpcMethod::NORMAL_RPC,
                          channel),
      rpcmethod_StopSdk_(Engine_method_names[4], options.suffix_for_stats(), ::grpc::internal::RpcMethod::NORMAL_RPC,
                         channel),
      rpcmethod_PipelineInference_(Engine_method_names[5], options.suffix_for_stats(),
                                   ::grpc::internal::RpcMethod::NORMAL_RPC, channel),
      rpcmethod_GetPipelineResult_(Engine_method_names[6], options.suffix_for_stats(),
                                   ::grpc::internal::RpcMethod::NORMAL_RPC, channel),
      rpcmethod_SetServiceFeature_(Engine_method_names[7], options.suffix_for_stats(),
                                   ::grpc::internal::RpcMethod::NORMAL_RPC, channel),
      rpcmethod_GetServiceActualInfo_(Engine_method_names[8], options.suffix_for_stats(),
                                      ::grpc::internal::RpcMethod::NORMAL_RPC, channel) {}

::grpc::Status Engine::Stub::Status(::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
                                    ::NrealAiTool::StatusReply* response) {
    return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::NrealAiTool::StatusReply,
                                                ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_Status_, context, request, response);
}

void Engine::Stub::async::Status(::grpc::ClientContext* context, const ::google::protobuf::Empty* request,
                                 ::NrealAiTool::StatusReply* response, std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::NrealAiTool::StatusReply,
                                         ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Status_, context, request, response, std::move(f));
}

void Engine::Stub::async::Status(::grpc::ClientContext* context, const ::google::protobuf::Empty* request,
                                 ::NrealAiTool::StatusReply* response, ::grpc::ClientUnaryReactor* reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Status_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::StatusReply>* Engine::Stub::PrepareAsyncStatusRaw(
    ::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::NrealAiTool::StatusReply, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite,
        ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Status_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::StatusReply>* Engine::Stub::AsyncStatusRaw(
    ::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
    auto* result = this->PrepareAsyncStatusRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status Engine::Stub::Upload(::grpc::ClientContext* context, const ::NrealAiTool::UploadRequest& request,
                                    ::NrealAiTool::UploadReply* response) {
    return ::grpc::internal::BlockingUnaryCall< ::NrealAiTool::UploadRequest, ::NrealAiTool::UploadReply,
                                                ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_Upload_, context, request, response);
}

void Engine::Stub::async::Upload(::grpc::ClientContext* context, const ::NrealAiTool::UploadRequest* request,
                                 ::NrealAiTool::UploadReply* response, std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall< ::NrealAiTool::UploadRequest, ::NrealAiTool::UploadReply,
                                         ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Upload_, context, request, response, std::move(f));
}

void Engine::Stub::async::Upload(::grpc::ClientContext* context, const ::NrealAiTool::UploadRequest* request,
                                 ::NrealAiTool::UploadReply* response, ::grpc::ClientUnaryReactor* reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Upload_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::UploadReply>* Engine::Stub::PrepareAsyncUploadRaw(
    ::grpc::ClientContext* context, const ::NrealAiTool::UploadRequest& request, ::grpc::CompletionQueue* cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::NrealAiTool::UploadReply, ::NrealAiTool::UploadRequest, ::grpc::protobuf::MessageLite,
        ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Upload_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::UploadReply>* Engine::Stub::AsyncUploadRaw(
    ::grpc::ClientContext* context, const ::NrealAiTool::UploadRequest& request, ::grpc::CompletionQueue* cq) {
    auto* result = this->PrepareAsyncUploadRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status Engine::Stub::ResetSdk(::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
                                      ::NrealAiTool::ResetSdkReply* response) {
    return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::NrealAiTool::ResetSdkReply,
                                                ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_ResetSdk_, context, request, response);
}

void Engine::Stub::async::ResetSdk(::grpc::ClientContext* context, const ::google::protobuf::Empty* request,
                                   ::NrealAiTool::ResetSdkReply* response, std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::NrealAiTool::ResetSdkReply,
                                         ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_ResetSdk_, context, request, response, std::move(f));
}

void Engine::Stub::async::ResetSdk(::grpc::ClientContext* context, const ::google::protobuf::Empty* request,
                                   ::NrealAiTool::ResetSdkReply* response, ::grpc::ClientUnaryReactor* reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_ResetSdk_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::ResetSdkReply>* Engine::Stub::PrepareAsyncResetSdkRaw(
    ::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::NrealAiTool::ResetSdkReply, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite,
        ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ResetSdk_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::ResetSdkReply>* Engine::Stub::AsyncResetSdkRaw(
    ::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
    auto* result = this->PrepareAsyncResetSdkRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status Engine::Stub::StartSdk(::grpc::ClientContext* context, const ::NrealAiTool::StartSdkRequest& request,
                                      ::NrealAiTool::StartSdkReply* response) {
    return ::grpc::internal::BlockingUnaryCall< ::NrealAiTool::StartSdkRequest, ::NrealAiTool::StartSdkReply,
                                                ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_StartSdk_, context, request, response);
}

void Engine::Stub::async::StartSdk(::grpc::ClientContext* context, const ::NrealAiTool::StartSdkRequest* request,
                                   ::NrealAiTool::StartSdkReply* response, std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall< ::NrealAiTool::StartSdkRequest, ::NrealAiTool::StartSdkReply,
                                         ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_StartSdk_, context, request, response, std::move(f));
}

void Engine::Stub::async::StartSdk(::grpc::ClientContext* context, const ::NrealAiTool::StartSdkRequest* request,
                                   ::NrealAiTool::StartSdkReply* response, ::grpc::ClientUnaryReactor* reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_StartSdk_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::StartSdkReply>* Engine::Stub::PrepareAsyncStartSdkRaw(
    ::grpc::ClientContext* context, const ::NrealAiTool::StartSdkRequest& request, ::grpc::CompletionQueue* cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::NrealAiTool::StartSdkReply, ::NrealAiTool::StartSdkRequest, ::grpc::protobuf::MessageLite,
        ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartSdk_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::StartSdkReply>* Engine::Stub::AsyncStartSdkRaw(
    ::grpc::ClientContext* context, const ::NrealAiTool::StartSdkRequest& request, ::grpc::CompletionQueue* cq) {
    auto* result = this->PrepareAsyncStartSdkRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status Engine::Stub::StopSdk(::grpc::ClientContext* context, const ::NrealAiTool::StopSdkRequest& request,
                                     ::NrealAiTool::StopSdkReply* response) {
    return ::grpc::internal::BlockingUnaryCall< ::NrealAiTool::StopSdkRequest, ::NrealAiTool::StopSdkReply,
                                                ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_StopSdk_, context, request, response);
}

void Engine::Stub::async::StopSdk(::grpc::ClientContext* context, const ::NrealAiTool::StopSdkRequest* request,
                                  ::NrealAiTool::StopSdkReply* response, std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall< ::NrealAiTool::StopSdkRequest, ::NrealAiTool::StopSdkReply,
                                         ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_StopSdk_, context, request, response, std::move(f));
}

void Engine::Stub::async::StopSdk(::grpc::ClientContext* context, const ::NrealAiTool::StopSdkRequest* request,
                                  ::NrealAiTool::StopSdkReply* response, ::grpc::ClientUnaryReactor* reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_StopSdk_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::StopSdkReply>* Engine::Stub::PrepareAsyncStopSdkRaw(
    ::grpc::ClientContext* context, const ::NrealAiTool::StopSdkRequest& request, ::grpc::CompletionQueue* cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::NrealAiTool::StopSdkReply, ::NrealAiTool::StopSdkRequest, ::grpc::protobuf::MessageLite,
        ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopSdk_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::StopSdkReply>* Engine::Stub::AsyncStopSdkRaw(
    ::grpc::ClientContext* context, const ::NrealAiTool::StopSdkRequest& request, ::grpc::CompletionQueue* cq) {
    auto* result = this->PrepareAsyncStopSdkRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status Engine::Stub::PipelineInference(::grpc::ClientContext* context,
                                               const ::NrealAiTool::PipelineInferenceRequest& request,
                                               ::NrealAiTool::PipelineInferenceReply* response) {
    return ::grpc::internal::BlockingUnaryCall< ::NrealAiTool::PipelineInferenceRequest,
                                                ::NrealAiTool::PipelineInferenceReply, ::grpc::protobuf::MessageLite,
                                                ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_PipelineInference_, context, request, response);
}

void Engine::Stub::async::PipelineInference(::grpc::ClientContext* context,
                                            const ::NrealAiTool::PipelineInferenceRequest* request,
                                            ::NrealAiTool::PipelineInferenceReply* response,
                                            std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall< ::NrealAiTool::PipelineInferenceRequest, ::NrealAiTool::PipelineInferenceReply,
                                         ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_PipelineInference_, context, request, response, std::move(f));
}

void Engine::Stub::async::PipelineInference(::grpc::ClientContext* context,
                                            const ::NrealAiTool::PipelineInferenceRequest* request,
                                            ::NrealAiTool::PipelineInferenceReply* response,
                                            ::grpc::ClientUnaryReactor* reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_PipelineInference_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::PipelineInferenceReply>*
Engine::Stub::PrepareAsyncPipelineInferenceRaw(::grpc::ClientContext* context,
                                               const ::NrealAiTool::PipelineInferenceRequest& request,
                                               ::grpc::CompletionQueue* cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::NrealAiTool::PipelineInferenceReply, ::NrealAiTool::PipelineInferenceRequest, ::grpc::protobuf::MessageLite,
        ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PipelineInference_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::PipelineInferenceReply>* Engine::Stub::AsyncPipelineInferenceRaw(
    ::grpc::ClientContext* context, const ::NrealAiTool::PipelineInferenceRequest& request,
    ::grpc::CompletionQueue* cq) {
    auto* result = this->PrepareAsyncPipelineInferenceRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status Engine::Stub::GetPipelineResult(::grpc::ClientContext* context,
                                               const ::NrealAiTool::GetPipelineResultRequest& request,
                                               ::NrealAiTool::GetPipelineResultReply* response) {
    return ::grpc::internal::BlockingUnaryCall< ::NrealAiTool::GetPipelineResultRequest,
                                                ::NrealAiTool::GetPipelineResultReply, ::grpc::protobuf::MessageLite,
                                                ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_GetPipelineResult_, context, request, response);
}

void Engine::Stub::async::GetPipelineResult(::grpc::ClientContext* context,
                                            const ::NrealAiTool::GetPipelineResultRequest* request,
                                            ::NrealAiTool::GetPipelineResultReply* response,
                                            std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall< ::NrealAiTool::GetPipelineResultRequest, ::NrealAiTool::GetPipelineResultReply,
                                         ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_GetPipelineResult_, context, request, response, std::move(f));
}

void Engine::Stub::async::GetPipelineResult(::grpc::ClientContext* context,
                                            const ::NrealAiTool::GetPipelineResultRequest* request,
                                            ::NrealAiTool::GetPipelineResultReply* response,
                                            ::grpc::ClientUnaryReactor* reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_GetPipelineResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::GetPipelineResultReply>*
Engine::Stub::PrepareAsyncGetPipelineResultRaw(::grpc::ClientContext* context,
                                               const ::NrealAiTool::GetPipelineResultRequest& request,
                                               ::grpc::CompletionQueue* cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::NrealAiTool::GetPipelineResultReply, ::NrealAiTool::GetPipelineResultRequest, ::grpc::protobuf::MessageLite,
        ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPipelineResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::GetPipelineResultReply>* Engine::Stub::AsyncGetPipelineResultRaw(
    ::grpc::ClientContext* context, const ::NrealAiTool::GetPipelineResultRequest& request,
    ::grpc::CompletionQueue* cq) {
    auto* result = this->PrepareAsyncGetPipelineResultRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status Engine::Stub::SetServiceFeature(::grpc::ClientContext* context,
                                               const ::NrealAiTool::SetServiceFeatureRequest& request,
                                               ::NrealAiTool::SetServiceFeatureReply* response) {
    return ::grpc::internal::BlockingUnaryCall< ::NrealAiTool::SetServiceFeatureRequest,
                                                ::NrealAiTool::SetServiceFeatureReply, ::grpc::protobuf::MessageLite,
                                                ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_SetServiceFeature_, context, request, response);
}

void Engine::Stub::async::SetServiceFeature(::grpc::ClientContext* context,
                                            const ::NrealAiTool::SetServiceFeatureRequest* request,
                                            ::NrealAiTool::SetServiceFeatureReply* response,
                                            std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall< ::NrealAiTool::SetServiceFeatureRequest, ::NrealAiTool::SetServiceFeatureReply,
                                         ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_SetServiceFeature_, context, request, response, std::move(f));
}

void Engine::Stub::async::SetServiceFeature(::grpc::ClientContext* context,
                                            const ::NrealAiTool::SetServiceFeatureRequest* request,
                                            ::NrealAiTool::SetServiceFeatureReply* response,
                                            ::grpc::ClientUnaryReactor* reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_SetServiceFeature_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::SetServiceFeatureReply>*
Engine::Stub::PrepareAsyncSetServiceFeatureRaw(::grpc::ClientContext* context,
                                               const ::NrealAiTool::SetServiceFeatureRequest& request,
                                               ::grpc::CompletionQueue* cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::NrealAiTool::SetServiceFeatureReply, ::NrealAiTool::SetServiceFeatureRequest, ::grpc::protobuf::MessageLite,
        ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetServiceFeature_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::SetServiceFeatureReply>* Engine::Stub::AsyncSetServiceFeatureRaw(
    ::grpc::ClientContext* context, const ::NrealAiTool::SetServiceFeatureRequest& request,
    ::grpc::CompletionQueue* cq) {
    auto* result = this->PrepareAsyncSetServiceFeatureRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status Engine::Stub::GetServiceActualInfo(::grpc::ClientContext* context,
                                                  const ::NrealAiTool::GetServiceActualInfoRequest& request,
                                                  ::NrealAiTool::GetServiceActualInfoReply* response) {
    return ::grpc::internal::BlockingUnaryCall< ::NrealAiTool::GetServiceActualInfoRequest,
                                                ::NrealAiTool::GetServiceActualInfoReply, ::grpc::protobuf::MessageLite,
                                                ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_GetServiceActualInfo_, context, request, response);
}

void Engine::Stub::async::GetServiceActualInfo(::grpc::ClientContext* context,
                                               const ::NrealAiTool::GetServiceActualInfoRequest* request,
                                               ::NrealAiTool::GetServiceActualInfoReply* response,
                                               std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall< ::NrealAiTool::GetServiceActualInfoRequest,
                                         ::NrealAiTool::GetServiceActualInfoReply, ::grpc::protobuf::MessageLite,
                                         ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_GetServiceActualInfo_, context, request, response, std::move(f));
}

void Engine::Stub::async::GetServiceActualInfo(::grpc::ClientContext* context,
                                               const ::NrealAiTool::GetServiceActualInfoRequest* request,
                                               ::NrealAiTool::GetServiceActualInfoReply* response,
                                               ::grpc::ClientUnaryReactor* reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_GetServiceActualInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::GetServiceActualInfoReply>*
Engine::Stub::PrepareAsyncGetServiceActualInfoRaw(::grpc::ClientContext* context,
                                                  const ::NrealAiTool::GetServiceActualInfoRequest& request,
                                                  ::grpc::CompletionQueue* cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::NrealAiTool::GetServiceActualInfoReply, ::NrealAiTool::GetServiceActualInfoRequest,
        ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), cq, rpcmethod_GetServiceActualInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NrealAiTool::GetServiceActualInfoReply>*
Engine::Stub::AsyncGetServiceActualInfoRaw(::grpc::ClientContext* context,
                                           const ::NrealAiTool::GetServiceActualInfoRequest& request,
                                           ::grpc::CompletionQueue* cq) {
    auto* result = this->PrepareAsyncGetServiceActualInfoRaw(context, request, cq);
    result->StartCall();
    return result;
}

Engine::Service::Service() {
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        Engine_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<Engine::Service, ::google::protobuf::Empty, ::NrealAiTool::StatusReply,
                                               ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
            [](Engine::Service* service, ::grpc::ServerContext* ctx, const ::google::protobuf::Empty* req,
               ::NrealAiTool::StatusReply* resp) { return service->Status(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        Engine_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<Engine::Service, ::NrealAiTool::UploadRequest,
                                               ::NrealAiTool::UploadReply, ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](Engine::Service* service, ::grpc::ServerContext* ctx, const ::NrealAiTool::UploadRequest* req,
               ::NrealAiTool::UploadReply* resp) { return service->Upload(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        Engine_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<Engine::Service, ::google::protobuf::Empty, ::NrealAiTool::ResetSdkReply,
                                               ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
            [](Engine::Service* service, ::grpc::ServerContext* ctx, const ::google::protobuf::Empty* req,
               ::NrealAiTool::ResetSdkReply* resp) { return service->ResetSdk(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        Engine_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<Engine::Service, ::NrealAiTool::StartSdkRequest,
                                               ::NrealAiTool::StartSdkReply, ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](Engine::Service* service, ::grpc::ServerContext* ctx, const ::NrealAiTool::StartSdkRequest* req,
               ::NrealAiTool::StartSdkReply* resp) { return service->StartSdk(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        Engine_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<Engine::Service, ::NrealAiTool::StopSdkRequest,
                                               ::NrealAiTool::StopSdkReply, ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](Engine::Service* service, ::grpc::ServerContext* ctx, const ::NrealAiTool::StopSdkRequest* req,
               ::NrealAiTool::StopSdkReply* resp) { return service->StopSdk(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        Engine_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<Engine::Service, ::NrealAiTool::PipelineInferenceRequest,
                                               ::NrealAiTool::PipelineInferenceReply, ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](Engine::Service* service, ::grpc::ServerContext* ctx, const ::NrealAiTool::PipelineInferenceRequest* req,
               ::NrealAiTool::PipelineInferenceReply* resp) { return service->PipelineInference(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        Engine_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<Engine::Service, ::NrealAiTool::GetPipelineResultRequest,
                                               ::NrealAiTool::GetPipelineResultReply, ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](Engine::Service* service, ::grpc::ServerContext* ctx, const ::NrealAiTool::GetPipelineResultRequest* req,
               ::NrealAiTool::GetPipelineResultReply* resp) { return service->GetPipelineResult(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        Engine_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<Engine::Service, ::NrealAiTool::SetServiceFeatureRequest,
                                               ::NrealAiTool::SetServiceFeatureReply, ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](Engine::Service* service, ::grpc::ServerContext* ctx, const ::NrealAiTool::SetServiceFeatureRequest* req,
               ::NrealAiTool::SetServiceFeatureReply* resp) { return service->SetServiceFeature(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        Engine_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<Engine::Service, ::NrealAiTool::GetServiceActualInfoRequest,
                                               ::NrealAiTool::GetServiceActualInfoReply, ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](Engine::Service* service, ::grpc::ServerContext* ctx,
               const ::NrealAiTool::GetServiceActualInfoRequest* req, ::NrealAiTool::GetServiceActualInfoReply* resp) {
                return service->GetServiceActualInfo(ctx, req, resp);
            },
            this)));
}

Engine::Service::~Service() {}

::grpc::Status Engine::Service::Status(::grpc::ServerContext* context, const ::google::protobuf::Empty* request,
                                       ::NrealAiTool::StatusReply* response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Engine::Service::Upload(::grpc::ServerContext* context, const ::NrealAiTool::UploadRequest* request,
                                       ::NrealAiTool::UploadReply* response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Engine::Service::ResetSdk(::grpc::ServerContext* context, const ::google::protobuf::Empty* request,
                                         ::NrealAiTool::ResetSdkReply* response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Engine::Service::StartSdk(::grpc::ServerContext* context, const ::NrealAiTool::StartSdkRequest* request,
                                         ::NrealAiTool::StartSdkReply* response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Engine::Service::StopSdk(::grpc::ServerContext* context, const ::NrealAiTool::StopSdkRequest* request,
                                        ::NrealAiTool::StopSdkReply* response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Engine::Service::PipelineInference(::grpc::ServerContext* context,
                                                  const ::NrealAiTool::PipelineInferenceRequest* request,
                                                  ::NrealAiTool::PipelineInferenceReply* response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Engine::Service::GetPipelineResult(::grpc::ServerContext* context,
                                                  const ::NrealAiTool::GetPipelineResultRequest* request,
                                                  ::NrealAiTool::GetPipelineResultReply* response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Engine::Service::SetServiceFeature(::grpc::ServerContext* context,
                                                  const ::NrealAiTool::SetServiceFeatureRequest* request,
                                                  ::NrealAiTool::SetServiceFeatureReply* response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Engine::Service::GetServiceActualInfo(::grpc::ServerContext* context,
                                                     const ::NrealAiTool::GetServiceActualInfoRequest* request,
                                                     ::NrealAiTool::GetServiceActualInfoReply* response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

}  // namespace NrealAiTool
